### PR TITLE
fix #335 Assertion IsArray() failed on CANCEL_ORDER for BitFinex exchange

### LINKED ISSUE #335: Assertion `IsArray()' failed on CANCEL_ORDER for BitFinex exchange
**Describe the bug**
When sending CANCEL_ORDER request for bitfinex a providing an EventQueue, I get the folowing failed assertion:

`rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]: Assertion `IsArray()' failed.
`

The assertion fails because the function
ExecutionManagementServiceBitfinex::extractOrderInfo assumes that it is called with an array type for argument `const rj::Value& x` but it is called with an individual value for x and calls operator[] on that x.

The cause for this is:
ExecutionManagementServiceBitfinex::extractOrderInfoFromRequest handles CREATE_ORDER and CANCEL_ORDER in the same manner:

```
void extractOrderInfoFromRequest(std::vector<Element>& elementList, const Request& request, const Request::Operation operation, const rj::Document& document) override {
    if (operation == Request::Operation::CREATE_ORDER || operation == Request::Operation::CANCEL_ORDER) {
      Element element;
      this->extractOrderInfo(element, document[4][0]);
      elementList.emplace_back(std::move(element));
    } else if (operation == Request::Operation::GET_ORDER) {
```

But looking at the responses which we receive from bitfinex there is a difference. You can see, that for CREATE_ORDER the 4th entry is an array of arrays, while for CANCEL_ORDER it is just an array.

Response for CREATE_ORDER:
"[1670537236,\"on-req\",null,null,[[109833343300,null,21121987,\"tTESTBTC:TESTUSD\",1670537236127,1670537236127,0.1,0.1,\"EXCHANGE LIMIT\",null,null,null,0,\"ACTIVE\",null,null,1000,0,0,0,null,null,null,0,0,null,null,null,\"API>BFX\",null,null,{}]],null,\"SUCCESS\",\"Submitting 1 orders.\"]"

Response CANCEL_ORDER:
"[1670537288153,\"oc-req\",null,null,[109833343300,null,21121987,\"tTESTBTC:TESTUSD\",1670537236127,1670537236128,0.1,0.1,\"EXCHANGE LIMIT\",null,null,null,0,\"ACTIVE\",null,null,1000,0,0,0,null,null,null,0,0,null,null,null,\"API>BFX\",null,null,{}],null,\"SUCCESS\",\"Submitted for cancellation; waiting for confirmation (ID: 109833343300).\"]"

**To Reproduce**
Almost pseudo code:

ccapi::Request request{ccapi::Request::Operation::CANCEL_ORDER, CCAPI_EXCHANGE_NAME_BITFINEX, "myinstrument")};
request->appendParam({
      {"ORDER_ID", "myorderid"}
});
ccapi::Queue<ccapi::Event> event_queue;
session.sendRequest(request, &event_queue); // <--- assertion fails on this call

**Expected behavior**
Assertion should not fail.

**Additional context**
git commit 077fbf70a187a64581bc0b4fd71e841bf4657930

### PR DESCRIPTION
**Pull request by vakakav**
This is the fix for issues #335.

### CODE REVIEW

File: include/ccapi_cpp/service/ccapi_execution_management_service_bitfinex.h [hunk 1]
```diff
@@ -227,10 +227,14 @@ class ExecutionManagementServiceBitfinex : public ExecutionManagementService {
...
                                    const rj::Document& document) override {
-    if (operation == Request::Operation::CREATE_ORDER || operation == Request::Operation::CANCEL_ORDER) {
+    if (operation == Request::Operation::CREATE_ORDER) {
       Element element;
       this->extractOrderInfo(element, document[4][0]);
       elementList.emplace_back(std::move(element));
+    } else if (operation == Request::Operation::CANCEL_ORDER) {
+      Element element;
+      this->extractOrderInfo(element, document[4]);
+      elementList.emplace_back(std::move(element));
```
Comment (vakakav) [inline include/ccapi_cpp/service/ccapi_execution_management_service_bitfinex.h:237]: Here are the demo responses from bitfinex for explanation:

submit order (aka CREATE_ORDER):
[
  MTS, 
  TYPE, 
  MESSAGE_ID, 
  null,
  
  [[
     ID,
     GID,
     CID,
     SYMBOL,
     MTS_CREATE, 
     MTS_UPDATE, 
     AMOUNT, 
     AMOUNT_ORIG, 
     TYPE,
     TYPE_PREV,
     MTS_TIF,
     _PLACEHOLDER,
     FLAGS,
     ORDER_STATUS,
     _PLACEHOLDER,
     _PLACEHOLDER,
     PRICE,
     PRICE_AVG,
     PRICE_TRAILING,
     PRICE_AUX_LIMIT,
     _PLACEHOLDER,
     _PLACEHOLDER,
     _PLACEHOLDER,
     _PLACEHOLDER,
     HIDDEN, 
     PLACED_ID,
     _PLACEHOLDER,
     _PLACEHOLDER,
     ROUTING,
     _PLACEHOLDER,
     _PLACEHOLDER,
     META
   ],
   ]
   
  CODE, 
  STATUS, 
  TEXT
]
    
[1567590617.442,"on-req",null,null,[[30630788061,null,1567590617439,"tBTCUSD",1567590617439,1567590617439,0.001,0.001,"LIMIT",null,null,null,0,"ACTIVE",null,null,15,0,0,0,null,null,null,0,null,null,null,null,"API>BFX",null,null,null]],null,"SUCCESS","Submitting 1 orders."]


cancel order:
[
  MTS, 
  TYPE, 
  MESSAGE_ID, 
  null,
  
  [
     ID,
     GID,
     CID,
     SYMBOL,
     MTS_CREATE, 
     MTS_UPDATE, 
     AMOUNT, 
     AMOUNT_ORIG, 
     TYPE,
     TYPE_PREV,
     MTS_TIF,
     _PLACEHOLDER,
     FLAGS,
     ORDER_STATUS,
     _PLACEHOLDER,
     _PLACEHOLDER,
     PRICE,
     PRICE_AVG,
     PRICE_TRAILING,
     PRICE_AUX_LIMIT,
     _PLACEHOLDER,
     _PLACEHOLDER,
     _PLACEHOLDER,
     _PLACEHOLDER,
     HIDDEN, 
     PLACED_ID,     
     _PLACEHOLDER,
     _PLACEHOLDER,
     ROUTING,
     _PLACEHOLDER,
     _PLACEHOLDER,
     META
   ]
   
  CODE, 
  STATUS, 
  TEXT
]
    
[1568298355648,"oc-req",null,null,[30937950333,null,1568298279766,"tBTCUSD",1568298281000,1568298281000,0.001,0.001,"LIMIT",null,null,null,0,"ACTIVE",null,null,15,0,0,0,null,null,null,0,0,null,null,null,"API>BFX",null,null,null],null,"SUCCESS","Submitted for cancellation; waiting for confirmation (ID: 30937950333)."]
